  
//0: x = low; y = mid, z = high;
//1: while( x < y) { x++; }
//2: while( y < z) { y++; }
//3: assert(y = high);

.input low(filename="low.facts")
.decl low(x:number)
.input med(filename="med.facts")
.decl med(x:number)
.input high(filename="high.facts")
.decl high(x:number)

.output loop(filename="loop.ans")
.decl loop(line: number, x:number, y:number, z:number)

loop(0, l, m, h) :- low(l), med(m), high(h).

loop(1, x, y, z)   :- loop(0, x, y, z).
loop(1, x+1, y, z) :- loop(1, x, y, _), loop(0, _, _, z), x < y.

loop(2, x, y, z) :- loop(1, x, y, z), x >= y.
loop(2, x, y+1, z) :- loop(2, _, y, z), loop(1, x, _, _),  y < z.

loop(3, x, y, z) :- loop(2, x, y, z), y >= z.